services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network
    ports:
      - "8081:9428"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9428/api" ]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 30s


  frontend:
    build: ./front-end
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy